name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t your-docker-image-name:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push your-docker-image-name:latest

      - name: Install Render CLI
        run: |
          curl -sSL https://cli.render.com/install.sh | bash

      - name: Log in to Render
        run: |
          render login --apiKey ${{ secrets.RENDER_API_KEY }}

      - name: Deploy to Render
        run: |
          render deploy your-service-name --docker-image your-docker-image-name:latest
