name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "pratyay44" --password-stdin

      - name: Extract short SHA
        id: vars
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t pratyay44/qrcodewaiter:${{ env.GIT_SHA }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push pratyay44/qrcodewaiter:${{ env.GIT_SHA }}

      - name: Deploy to Render
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{"serviceId": "your-render-service-id", "dockerImage": "pratyay44/qrcodewaiter:${{ env.GIT_SHA }}"}' \
          https://api.render.com/v1/services/deploys
