name: CI/CD to Docker Hub and Render

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t edge007/qrcodewaiter:${{ env.GIT_SHA }} .
          docker push edge007/qrcodewaiter:${{ env.GIT_SHA }}

      - name: Deploy to Render
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
               -d '{"image":"edge007/qrcodewaiter:${{ env.GIT_SHA }}"}' \
               https://api.render.com/v1/services/your-render-service-id/deploys
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
